[theme]
primaryColor = "#2C6E49"            # Verde Escuro
backgroundColor = "#F0F7F4"         # Fundo Muito Claro
secondaryBackgroundColor = "#CCE3DC"  # Verde Claro
textColor = "#023047"               # Azul Escuro
font = "sans serif"